### ISSUE TITLE
Error JazzHandsSwift

### ISSUE THREAD

**Issue by Ravichandrane** [confile/JazzHandsSwift#1]
Hi :) 

I try to use JazzHandsSwift but I got some errors... I don't understand why :/ 

Someone could help me please :) 

![screen shot 2015-07-13 at 20 31 44](https://cloud.githubusercontent.com/assets/4774729/8657492/398e94fe-299e-11e5-8bde-c801495ac31b.png)

![screen shot 2015-07-13 at 20 34 07](https://cloud.githubusercontent.com/assets/4774729/8657536/8799ceb6-299e-11e5-9829-fd53109dca30.png)

**Comment by drmichaelgorski** [comment]
Do you have this in your pod file: 

```
pod 'JazzHands', '~> 2.0.0'
```

**Comment by Ravichandrane** [comment]
Yes of course but it installs the latest version...

**Comment by drmichaelgorski** [comment]
Have you tried clean and then build?

**Comment by Ravichandrane** [comment]
Yes I also try to start a test project I get still the latest version

**Comment by drmichaelgorski** [comment]
I just checked out the latest version of the example and it still works. Have you tried: 

https://github.com/confile/JazzHandsSwift/tree/master/TourTest

**Comment by Ravichandrane** [comment]
Finally I found where the problem come from, I get the problem only when I use Alamofire and SwiftyJson with 'use_frameworks!' in the podfile... Do you have an idea how can I fixe ? :) 

Thanks.

**Comment by drmichaelgorski** [comment]
I have no idea why it does not work together.

**Comment by drmichaelgorski** [comment]
I close this issue since it is not related to this project.
